### ISSUE TITLE
Proposal: Add `updated` to the output object. Populate it with the objects that have been updated.

### ISSUE THREAD

**Issue by malcolmvr** [Kikobeats/hyperdiff#11]
Usage code example:

```
const diff = require('hyperdiff')

const orig = [{ id: 1, a: 1 }]
const dist = [{ id: 1, a: 2 }]
const options = {
  compareObjects: true,
  compareFunction: null // defaults to lodash.isEqual
}

const result = diff(orig, dist, 'id', options)

console.log(result)
// {
//   added: [],
//   removed: [],
//   common: [],
//   updated: [{ id: 1, a: 2}]
// }
```

The salient points here are that an `options` parameter (optional) is added to the `hyperdiff` function. If `options.compareObjects` is `true` then the code will presume `orig` and `dist` are arrays of objects. The `compareFunction` parameter is optional. If not set lodash's `isEqual` function will be used to compare the objects. If set a function with parameters `(obj1, obj2)`, that returns truthy/falsey is expected.

This should be entirely backwards compatible. By going with a `options` object as the fourth parameter it can be used in the future to add more options to `hyperdiff` without adding a lot of parameters.

I'm willing to make a PR for this. Just want to gauge the appetite.

**Comment by malcolmvr** [comment]
Yes, that is precisely my use case.

**Comment by Kikobeats** [comment]
Nor sure if this is a generic case to add it into the library.

Why not create a separate library that use this for the purpose?

**Comment by malcolmvr** [comment]
I think it could make sense to include it here but perhaps a new library is best.

**Comment by Kikobeats** [comment]
My afraid is complicated the library too much. Probably we are talking about two things here.

- Add a new `updated` data field.
- Add a way to modify the API behavior.

Can you create separate PR's? 🙂
