### ISSUE TITLE
TypeScript Types Por Favor

### ISSUE THREAD

**Issue by shellscape** [Kikobeats/hyperdiff#24]
👋  Hey there. Thanks for this great little lib, works wonderfully. Adding typescript types to it would be a huge value, would love to see that if you have the time. Cheers

_ps. here's how I'm declaring it_

```ts
declare module 'hyperdiff' {
  interface HyperdiffResult<TElements = any> {
    added: TElements[];
    common: TElements[];
    removed: TElements[];
  }

  const diff: <TElements = any>(from: TElements[], to: TElements[]) => HyperdiffResult<TElements>;

  export = diff;
}
```

**Comment by Kikobeats** [comment]
Hey, Can you make a PR? 🙏

**Comment by shellscape** [comment]
Not at the moment :) The code block above should be good to get you started

**Comment by Kikobeats** [comment]
closing since it's a real issue, just something nice to have 🙂

**Comment by shellscape** [comment]
I mean, it's a feature request and you were provided code. Odd way to maintain a project ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
