### ISSUE TITLE
id field cannot be a string

### ISSUE THREAD

**Issue by gainxglobal** [Kikobeats/hyperdiff#8]
The documentation indicates that the id field can be a string. However this doesn't seem to be the case. The example code:

```
const diff = require('hyperdiff')
var result = diff(
  [
    {id: 1, name: 'a'},
    {id: 2, name: 'b'},
    {id: 3, name: 'c'},
    {id: 4, name: 'd'},
    {id: 5, name: 'e'}
  ],
  [
    {id: 1, name: 'a'},
    {id: 2, name: 'b'},
    {id: 7, name: 'e'}
  ],
  'id'
)
```

Generates an error, "TypeError: props.every is not a function" at /node_modules/hyperdiff/lib/index.js:14:16

**Comment by Kikobeats** [comment]
checking tests looks like the documentation is outdated in this aspect:
https://github.com/Kikobeats/hyperdiff/blob/master/test/multiple-ids-collection.js#L29

Not sure if your error is related to the thing that you are you saying.

Could be easy to write a test for verifying it. PR are welcome 🙂

**Comment by malcolmvr** [comment]
I've made changes on a local branch for this and am ready to create a pull request. I'm unable to push my branch - `ERROR: Permission to Kikobeats/hyperdiff.git denied to malcolmvr`.
This is my first time making a pull request so I'm not sure if I need to be granted access to push or if I'm not doing this correctly. If you could advise that would be great.

(I was logged in with a different account, gainxglobal, on my initial comment. Am switching to malcolmvr now.)

**Comment by malcolmvr** [comment]
Thanks. Created PR #10.
